name: Auto-describe
on: 
  issue_comment:
    types: [created] 

jobs:
  describe:
    permissions:
      issues: write
    if: startsWith(github.event.comment.body, '/assign')
    runs-on: ubuntu-latest
    steps:
    - name: Change label to "auto-assigned"
      run: |
        gh issue edit $ISSUE --add-label "dispatch" --repo $REPO
      env:
        ISSUE: ${{ github.event.issue.number }}
        REPO: ${{ github.event.repository.full_name }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Get issue author & check if they are a collaborator
      run: |
        AUTHOR=$(gh issue view $ISSUE --json author | jq -r '.author.login')
        IS_COLLABORATOR=$(gh api /repos/$REPO/collaborators/$AUTHOR --silent --fail || echo "false")
    
        if [[ "$IS_COLLABORATOR" != "false" ]]; then
          gh issue edit $ISSUE --assignee "$AUTHOR" --repo $REPO
          echo "Assigned issue to $AUTHOR"
        else
          OWNER=$(gh repo view $REPO --json owner | jq -r '.owner.login')
          gh issue edit $ISSUE --assignee "$OWNER" --repo $REPO
          echo "Assigning to owner, $AUTHOR is not a collaborator."
        fi
      env:
        ISSUE: ${{ github.event.issue.number }}
        REPO: ${{ github.event.repository.full_name }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
