# This is a basic workflow to help you get started with Actions dummy-commit

name: Default workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  workflow_dispatch:
    inputs:
      customer:
        description: 'Customer symbol'
        required: true
        default: 'A_CORP'
        type: choice
        options:
        - A_CORP
        - A_BANK
        - A_WAREHOUSE
      operator_name:
        description: 'Your name'
        required: false
        type: string
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_my_app:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Going sleep..."
          sleep 10
          echo "... nice, now I'm ready to work"

      - name: Testing input parameters for manual run
        run: |
          echo "The customer is $CUSTOMER"
          echo "The operator is $OPERATOR"
        env:
          CUSTOMER: ${{ inputs.customer }}
          OPERATOR: ${{ inputs.operator_name }}
