name: OpenAI API curl
on: 
  workflow_dispatch:
  

jobs:
  chat:
    if: startsWith(github.event.comment.body, '/chat')
    runs-on: ubuntu-latest
    steps:
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Wysyłanie zapytania do OpenAI API
        run: |
          curl -X POST "https://api.openai.com/v1/chat/completions" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4o-mini-2024-07-18",
            "messages": [{"role": "user", "content": "You are servicing a repository of python function which converts input strings into uppercase or lowercase. Someone has just written a comment on a pull request. Try to understand the message and write something what makes sense. The message is: ${{ github.event.comment.body }}"}]
          }' > output.json

      - name: Wyświetlenie odpowiedzi
        run: cat output.json
