name: OpenAI API curl
on: 
  issue_comment:
    types: [created] 

jobs:
  chat:
    permissions:
      pull-requests: write
    if: startsWith(github.event.comment.body, '/chat')
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload 
        run: echo '${{ toJson(github.event) }}'

      - name: Send request to OpenAI
        id: openai_response
        run: |
          DESC="You are servicing a repository of python function which converts input strings into uppercase or lowercase. Someone has just written a comment on a pull request. Currently the entire development team is on vacation. Try to understand the message and write something what makes sense. Do not tell that the team is absent, just try to pretend that you are developer. Try to personalize the message as possible. If you sign your response please use name Martik Bartik. The message is: " 
          ESCAPED_TEXT=$(echo "$DESC $TEXT" | sed "s/'/\\\'/g" | sed 's/"/\\\"/g' | tr '\n' ' ')
          JSON="{ \"model\": \"gpt-4o-mini-2024-07-18\", \"messages\": [{\"role\": \"user\", \"content\": \"$ESCAPED_TEXT\"}] }"
          
          RESULT=$(curl -X POST "https://api.openai.com/v1/chat/completions" \
                        -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
                        -H "Content-Type: application/json" \
                        -d "$JSON")

          RESPONSE=$(echo $RESULT | jq -r '.choices[0].message.content')       
          ESCAPED_RESPONSE=$(echo "$RESPONSE" | sed "s/'/\\\'/g" | sed 's/"/\\\"/g' | tr '\n' ' ')
          echo "----"
          echo $ESCAPED_RESPONSE
          echo "----"
          # echo "RESPONSE=\"$ESCAPED_RESPONSE\"" >> $GITHUB_OUTPUT
          echo "RESPONSE=$ESCAPED_RESPONSE" >> $GITHUB_OUTPUT
        env:
          TEXT: ${{ github.event.comment.body }}

      - name: Write the comment
        run: gh issue comment $ISSUE --body "$RESPONSE" --repo $REPO
        env:
          ISSUE: ${{ github.event.issue.number }}
          RESPONSE: ${{ steps.openai_response.outputs.RESPONSE }}
          REPO: ${{ github.event.repository.full_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

