ULname: OpenAI API curl
on: 
  issue_comment:
    types: [created]
  

jobs:
  chat:
    permissions:
      issues: write
    if: startsWith(github.event.comment.body, '/chat')
    runs-on: ubuntu-latest
    steps:
      - name: Debug event payload 
        run: echo '${{ toJson(github.event) }}'
        
      - name: Pobranie repozytorium
        uses: actions/checkout@v4

      - name: Wysyłanie zapytania do OpenAI API
        run: |
          DESC="You are servicing a repository of python function which converts input strings into uppercase or lowercase. Someone has just written a comment on a pull request. Currently the entire development team is on vacation. Try to understand the message and write something what makes sense. Do not tell that the team is absent, just try to pretend that you are developer. Try to personalize the message as possible. The message is: " 
          ESCAPED_TEXT=$(echo "$DESC $TEXT" | sed "s/'/\'/g")
          JSON="{ \"model\": \"gpt-4o-mini-2024-07-18\", \"messages\": [{\"role\": \"user\", \"content\": \"$ESCAPED_TEXT\"}] }"
          
          RESULT=$(curl -X POST "https://api.openai.com/v1/chat/completions" \
                        -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
                        -H "Content-Type: application/json" \
                        -d "$JSON")

          echo "----"
          echo $RESULT
          echo "----"

          RESPONSE=$(echo $RESULT | jq -r '.choices[0].message.content')
          gh issue comment $ISSUE --body "$RESPONSE" --repo $REPO
        env:
          TEXT: ${{ github.event.comment.body }}
          ISSUE: ${{ github.event.issue.number }}
          REPO: ${{ github.event.repository.full_name }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Wyświetlenie odpowiedzi
      #   run: cat output.json
