name: OpenAI Code Review

on:
  pull_request:
    types: [opened]

jobs:
  review_code:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    
    - name: Get PR diff
      run: |
        gh pr diff ${{ github.event.pull_request.number }} > diff.txt
        cat diff.txt
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Send code to OpenAI for review
      run: |
        echo '{
          "model": "gpt-4-turbo",
          "messages": [
              {"role": "system", "content": "You are an expert in programming. Review the code and suggest improvements."},
              {"role": "user", "content": "'"$(jq -Rs '.' < diff.txt)"'"}
            ]
          }' | jq .

        RESPONSE=$(curl -X POST "https://api.openai.com/v1/chat/completions" \
          -H "Authorization: Bearer ${{ secrets.OPENAI_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{
            "model": "gpt-4-turbo",
            "messages": [
              {"role": "system", "content": "You are an expert in programming. Review the code and suggest improvements, detect errors or bad practicies. Avoid being too polite and dont write compliments."},
              {"role": "user", "content": "'"$(jq -Rs '.' < diff.txt)"'"}
            ]
          }')
        echo "$RESPONSE" > review.txt

    - name: Post review as comment
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat review.txt)"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
