name: Run Python Tests & Build EXE

on:
  push:
    paths:
      - ".github/workflows/py_upper.yml"
      - "py-upper/**"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
        run: python -V
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sprawdzenie struktury katalogów
        run: pwd

      - name: Sprawdzenie struktury katalogów
        run: ls -R

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Check python version
        run: python -V

      - name: Install dependencies
        working-directory: py-upper
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Missing file: requirements.txt"

      - name: Run tests
        working-directory: py-upper
        run: pytest

  build:
    runs-on: windows-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE file
        working-directory: py-upper
        run: pyinstaller --onefile uppercase.py

      - name: Sprawdzenie struktury katalogów
        run: ls -R

      - name: Save artifacts to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: uppercase-exe
          path: py-upper/dist/uppercase.exe
